#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 45 -xoffset -0 -width 15 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Fantasque Sans Mono 10" <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) betterlockscreen -l ;;
                *Logout) i3exit logout;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
