#!/bin/bash

## Created By Aditya Shakya

MENU="$(dmenu -p  'System' <<< "Lock|Logout|Reboot|Shutdown")"
            case "$MENU" in
                *Lock) i3lock ;;
                *Logout) i3exit ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
