#!/bin/bash
acpiV=$(acpi)
value=$(echo $acpiV | cut -d " " -f 4 | sed -e 's/%//' | sed -e 's/,//')
con=$(echo $acpiV | cut -d " " -f 3 | sed -e 's/,//')

if [[ $value -lt 11 && "$con" == "Discharging" ]]; then
notify-send -u "Critical" "Low Battery" "$value% remaining"
fi
