#!/usr/bin/bash
export __GL_THREADED_OPTIMIZATIONS=1
export __GL_SHADER_DISK_CACHE=1
export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
export DXVK_HUD=fps
export __GL_SHADER_DISK_CACHE_PATH=/games/Battlenet/
PULSE_LATENCY_MSEC=60 WINEDEBUG=-all WINEARCH=win64 WINEPREFIX=~/.wine_battlenet wine "/home/hexdsl/.wine_battlenet/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe"

