#!/bin/bash

SRC="/home/damez/Videos/screencast"
DEST="/home/damez/Videos/convert"
DEST_EXT=mp4
HANDBRAKE_CLI=HandBrakeCLI

for FILE in "$SRC"/*
do
    filename=$(basename "$FILE")
    extension=${filename##*.}
    filename=${filename%.*}
    $HANDBRAKE_CLI --preset-import-file ~/Documents/scripts/videosa.json "videosa" -i "$FILE" -o "$DEST"/"$filename".$DEST_EXT
done
