#!/bin/bash


case "$(echo -e "Shutdown\nRestart\nLogout\nSuspend\nScreenshot" | dmenu \
    -nb "${COLOR_BACKGROUND:-#151515}" \
    -nf "${COLOR_DEFAULT:-#aaaaaa}" \
    -sf "${COLOR_HIGHLIGHT:-#589cc5}" \
    -sb "#1a1a1a" \
    -b -i -p \
    "Power:" )" in
        Shutdown) exec systemctl -i poweroff;;
        Restart) exec systemctl reboot;;
        Logout) exec i3-msg exit;;
        Suspend) exec systemctl suspend;;
        Screenshot) exec ~/Documents/scripts/screenshot.sh;;
esac
