#!/bin/bash
# File              : ytview
# License           : MIT License
# Author            : M. Nabil Adani <macroid48@gmail.com>
# Date              : Kamis, 05/09/2019 11:08 WIB
# Last Modified Date: Kamis, 05/09/2019 11:08 WIB
# Last Modified By  : M. Nabil Adani <macroid48@gmail.com>

# inspired by https://github.com/harimurtie/ndotfiles/blob/master/scripts/ytplay

#resolution="144p\n240p\n360p\n480p\n720p\n1080p"
resolution="360p\nlow\ndllow\naudio\ndlaudio"
dmenu="dmenu -x 190 -y 300 -w 1000 -fn Iosevka-11 -p resolution -i -l 10 "
selected=$(echo -e "$resolution" | $dmenu)

case "$selected" in
#  144p ) youtube-viewer --resolution 144p "$(xclip -selection clipboard -o | cut -d '&' -f 1)";;
#  240p ) youtube-viewer --resolution 240p "$(xclip -selection clipboard -o | cut -d '&' -f 1)";;
#  360p ) youtube-viewer --resolution 360p "$(xclip -selection clipboard -o | cut -d '&' -f 1)";;
#  480p ) youtube-viewer --resolution 480p "$(xclip -selection clipboard -o | cut -d '&' -f 1)";;
360p ) mpv --ytdl-format=18 "$(xclip -selection clipboard -o | cut -d '&' -f 1)";;
low ) mpv --ytdl-format=low "$(xclip -selection clipboard -o | cut -d '&' -f 1)";;
dllow ) youtube-dl -f low "$(xclip -selection clipboard -o | cut -d '&' -f 1)";;
audio ) mpv --ytdl-format=0 "$(xclip -selection clipboard -o | cut -d '&' -f 1)";;
dlaudio ) youtube-dl -f 0 "$(xclip -selection clipboard -o | cut -d '&' -f 1)";;
#  1080p ) youtube-viewer --resolution 1080p "$(xclip -selection clipboard -o | cut -d '&' -f 1)";;
esac
