#!/bin/bash
# File              : dmenu_aria2
# License           : MIT License
# Author            : M. Nabil Adani <macroid48@gmail.com>
# Date              : Rabu, 06/11/2019 04:51 WIB
# Last Modified Date: Rabu, 06/11/2019 17:55 WIB
# Last Modified By  : M. Nabil Adani <macroid48@gmail.com>



DMENU="dmenu -fn Iosevka-11 -l 5 -i -p Aria2"

url=$(cat ~/.cache/clipmenu.5.damez/line_cache_clipboard | sort -r | cut -c 21- | grep -Po '(http|https|ftp|ftps):\/\/\w.+' | $DMENU)
if [[ ! -z $url ]]; then
  aria2p call addUri -J "[[\"$url\"]]"
fi
