#!/bin/bash

DMENU='dmenu -fn 'TerminessTTF-8' -l 4 -i -b -nb #000000 -nf #999999 -sb #FFFFFF -sf #31658C'
choice=$(echo -e "nes\nsnes\npsp\nnds" | $DMENU)

case "$choice" in
    nes) fceux ;;
    snes) snes9x-gtk ;;
    psp) ppsspp ;;
    nds) desmume ;;
esac
