#!/bin/bash
##fetch
BASENAME='cat /etc/*release | grep PRETTY_NAME'
eval "$BASENAME"
#scfetch/Variables
OS=$PRETTY_NAME
USERNAME=$USER
WM=""
INIT=""
##scfetch/Desktop
if [ "$(XDG_CURRENT_DESKTOP)" ]; then
    desktop_type ='DE'
    WM="$(XDG_CURRENT_DESKTOP)"
    if ["$WM"=="*wm"];then
        desktop_type="WM"
fi

elif [ "$(DESKTOP_SESSION)"]; then
    desktop_type ='DE'
    WM="$DESKTOP_SESSION"
    if ["$WM"=="*wm"];then
        desktop_type="WM"
fi
else
    desktop_type='WM'
    WM=$(tail -n 1 "$(HOME)/.xinitrc" | cut -d ' ' -f 2)
    fi
