#!/bin/bash
# www.github.com/yedhink
#
# a system info scripted with love

name=$USER
distro="arch linux"
kernel=`uname -r`
wm=`wmctrl -m | grep -i name | awk '{print $2}'`
pkgs=`pacman -Qqs | wc -l`
she=`echo $SHELL | cut -d / -f 3`
dt=`date | awk '{print $1" "$2" "$3}'`
up=`uptime -p`

red="\e[31m"
grn="\e[32m"
ylw="\e[33m"
cyn="\e[36m"
blu="\e[34m"
prp="\e[35m"
bprp="\e[35;1m"
rst="\e[0m"

echo -e "  ${cyn}    distro ${rst}"  " $distro" " ${cyn} 		kernel ${rst}"  " $kernel "
echo -e "  ${grn}    wm     ${rst}"  " $wm   " " ${grn}      	pkgs    ${rst}"  "$pkgs   "
echo -e "  ${red}    shell  ${rst}"  " $she    " " ${red}   	up    ${rst}"  "  $up   "
echo -e "  ${prp}    editor ${rst}"  " $EDITOR   " " ${prp}     date    ${rst}"  "$dt   "
