#!/usr/bin/env sh
name=$USER
host=`hostname`
kernel=`uname -r`
pkgs=`pacman -Qqs | wc -l`
aurp=`pacman -Qm | wc -l`
flap=`flatpak list | wc -l`
age=`head -1 /var/log/pacman.log | cut -d\  -f1,2`
sens=`sensors | awk '/^Core 0:/ {print $3}'`
memz=`free -h | awk '/^Mem:/ {print $3 "/" $2}'`
cpum=`lscpu | grep "Model name: " |  cut -c 34-`
osname=`cat /etc/*-release | grep "PRETTY_NAME=" | cut -c 13-`
spcs=`df -h --total  | grep "total" | cut -c 17-22`
gpum=`cat /proc/driver/nvidia/gpus/0000\:01\:00.0/information | grep "Model:" | cut -c 11-`
upsy=`uptime -p`

echo "--Packages--"
echo "Repo          : $pkgs"
echo "AUR           : $aurp"
echo "Flatpaks      : $flap"
echo ""
echo "--System info--"
echo "user          : $name"
echo "Distro        : $osname"
echo "Host          : $host"
echo "kernel        : $kernel"
echo "uptime        : $upsy"
echo "GPU Model     : $gpum"
echo "CPU Model     : $cpum"
echo "CPU temp      : $sens"
echo "Free RAM      : $memz"
echo "Total storage : $spcs"
echo "Installed     : $age"
