#!/bin/bash
# use youtube-dl to query available stream qualities
# then prompt selection of streams to choose with rofi
# play the stream(s) with mpv by using its youtube-dl hook script

# only accept one argument, the url itself
if (($# != 1)); then
      exit 1
      fi

      # remove extra parameter in the url, sometimes it could cause failure
      url=$(cut -d '&' -f 1 < <(echo "$1"))

      # create a temp file for parsing purpose in /tmp
      format=/tmp/format-$(date +%s)
      youtube-dl -F "$url" > "$format"

      # delete temp file
      del_temp() {
            [[ -e "$format" ]] && rm "$format"
        }

    # delete temp file and exit if user doesn't select a stream
    check_empty() {
          if [[ -z $1 ]]; then
                  del_temp
                      exit 1
                        fi
                    }

                # play mpv with selected stream(s)
                # the window width is 640p.
                # the position is 0px from the right and 20px from the bottom.
                # since i'm using 2px border, there's 2px added for each direction.
                # adjust accordingly as you see fit for your desktop
                start_mpv() {
                      mpv --title="mpv-float" \
                                  --input-ipc-server=/tmp/mpv-socket \
                                      --loop-file \
                                          --ontop \
                                              --ytdl-format="$1" "$2"
                                          }

                                      # compose rofi prompt and get desired streams.
                                      if ! grep "video only" "$format"; then
                                            quality=$(grep -A100 'format code' "$format" | tail -n +2 \
                                                    | awk '{print $1}' \
                                                        | rofi -dmenu -i -p "Select quality")
                                              check_empty "$quality"

                                                start_mpv "$quality" "$url"
                                            else
                                                  video_quality=$(grep "video only" "$format" \
                                                          | awk '{print $1,"("$NF,$4,$2")"}' \
                                                              | rofi -dmenu -i -p "Select video resolution" | awk '{print $1}')
                                                    check_empty "$video_quality"

                                                      audio_quality=$(grep "audio only" "$format" \
                                                              | awk '{print $1,"("$NF,$7,$9")"}' \
                                                                  | rofi -dmenu -i -p "Select audio quality" | awk '{print $1}')
                                                        check_empty "$audio_quality"

                                                          quality="$video_quality"+"$audio_quality"

                                                            start_mpv "$quality" "$url"
    fi

    # clean up
    del_temp
