#!/bin/bash
status=${1}

if [[ $status == 'on' ]]; then
        polybar top -r
    elif [[ $status == 'off' ]]; then
            kill `ps -eo pid,args --cols=10000 | awk '/polybar top -r/ && $1 != PROCINFO["pid"] { print $1 }'`
        else
                echo 'Wrong argument! Only [on/off]'
fi
