#!/bin/bash

DMENU='dmenu -fn 'TerminessTTF-8' -i -b -nb #000000 -nf #999999 -sb #000000 -sf #31658C'
choice=$(echo -e "refresh\nkill\ndockon\ndockoff\nsteam\nkalkulator\ntelegram\nqutebrowser\ncadence\nmovie\npavucontrol\nvoltoggle\nvolmax\nvolhalf\nbright30\nbright50\nbright100\nplay\npause\nstop\nnext\nprev\nminimize\nmaximize\nfullscreen\nmpvcontrol\nclose\nscreenshot\nscreenshotarea\nscreenshotdelay\nyoutube\ncompton\nvokoscreen\nlogout\nreboot\nshutdown\nsuspend" | $DMENU)

case "$choice" in
      refresh) i3-msg restart ;;
      kill) ~/Documents/scripts/dmenu-kill-process ;;
      dockon) ~/Documents/scripts/killdock on >/dev/null 2>&1 & ;;
      dockoff) ~/Documents/scripts/killdock off >/dev/null 2>&1 & ;;
      steam) steam ;;
      kalkulator) ~/Documents/scripts/itung ;;
      telegram) telegram-desktop ;;
      qutebrowser) qutebrowser ;;
      cadence) cadence ;;
      movie) ~/Documents/scripts/film ;;
      pavucontrol) pavucontrol-qt ;;
      voltoggle) pamixer --toggle-mute ;;
      volmax) pamixer --set-volume 100 ;;
      volhalf) pamixer --set-volume 50 ;;
      bright30) xbacklight -set 30 ;;
      bright50) xbacklight -set 50 ;;
      bright100) xbacklight -set 100 ;;
      play) mpc play ;;
      pause) mpc toggle ;;
      stop) mpc stop ;;
      next) mpc next ;;
      prev) mpc prev ;;
      minimize) i3-msg move scratchpad ;;
      maximize) ~/Documents/scripts/hide ;;
      close) i3-msg kill & ;;
      fullscreen) i3-msg fullscreen ;;
      mpvcontrol) echo cycle pause | socat - ~/.config/mpv/socket ;;
      screenshot) ~/Documents/scripts/screenshot.sh & ;;
      screenshotarea) ~/Documents/scripts/screenshot.sh -s & ;;
      screenshotdelay) ~/Documents/scripts/scrots & ;;
      youtube) ~/Documents/scripts/ytplay & ;;
      compton) ~/Documents/scripts/compton-toggle.sh & ;;
      vokoscreen) vokoscreen & ;;
      logout) i3-msg exit & ;;
      reboot) exec systemctl reboot & ;;
      shutdown) exec systemctl -i poweroff & ;;
      suspend) exec systemctl suspend & ;;
esac

